---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)

library(ggthemes)
theme_set(theme_gdocs())
```

```{r}
data <- read_csv("data/word_frequencies.csv")

data %>%
  filter(n_synnouns == 0) %>%
  group_by(society) %>%
  top_n(100, freq) %>%
  ungroup() %>%
  group_by(word) %>%
  filter(n_distinct(society) == 1) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, freq, society)) %>% 
  ggplot(aes(freq, word, fill = society)) + 
  geom_col() + 
  scale_y_reordered() + 
  facet_wrap(~ society, nrow = 1, scales = "free")

data %>%
  filter(n_synverbs > 0) %>%
  group_by(society) %>%
  top_n(100, freq) %>%
  ungroup() %>%
  group_by(word) %>%
  filter(n_distinct(society) == 1) %>%
  ungroup() %>%
  group_by(society)  %>%
  top_n(20, freq) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, freq, society)) %>% 
  ggplot(aes(freq, word, fill = society)) + 
  geom_col() + 
  scale_y_reordered() + 
  facet_wrap(~ society, nrow = 1, scales = "free")
    
```

```{r}
words <- data %>%
  filter(n_synnouns == 0, n_synverbs > 0) %>%
  group_by(society) %>%
  top_n(500, freq) %>%
  ungroup() %>%
  group_by(word) %>%
  filter(n_distinct(society) == 1)
```


```{r}
get_lexicon <- function(name) {
  file_name <- sprintf("lexicons/enh_%s_lexicon.xlsx", name)
  readxl::read_xlsx(file_name) %>%
    janitor::clean_names() %>%
    select(term) %>%
    mutate(term = str_to_lower(term), 
           lexicon = name)
}

lexicon <- bind_rows(lapply(c("peace", "conflict"), get_lexicon)) %>%
  group_by(term) %>%
  filter(n_distinct(lexicon) == 1) %>%
  ungroup()

data %>%
  rename(term = word) %>%
  left_join(lexicon, by = "term") %>%
  filter(!is.na(lexicon)) %>%
  select(society, term, lexicon, freq) %>%
  group_by(society, lexicon) %>%
  mutate(freq_rank = rank(-freq)) %>%
  filter(freq_rank <= 100) %>%
  ggplot(aes(freq_rank, freq, color = lexicon)) + 
  geom_line(size=1.3) +
  facet_wrap(~ society, nrow = 1, scales = "free_y") + 
  scale_x_log10() + 
  scale_y_log10(labels = scales::comma_format()) + 
  labs(title = "Each country group is using a similar \ndistributions of peaceful and conflict terms (from the original lexicon)",
       subtitle = "Top 100 words in each Society-Lexicon group.",
       x = "LOG Rank",
       y = "LOG Frequency")

lexicon.new <- read_csv("lexicons/top_words_lexicon.csv")

data %>%
  rename(term = word) %>%
  left_join(lexicon.new, by = "term") %>%
  filter(!is.na(lexicon)) %>%
  select(society, term, lexicon, freq) %>%
  group_by(society, lexicon) %>%
  mutate(freq_rank = rank(-freq)) %>%
  filter(freq_rank <= 100) %>%
  ggplot(aes(freq_rank, freq, color = lexicon)) + 
  geom_line(size=1.3) +
  facet_wrap(~ society, nrow = 1, scales = "free_y") + 
  scale_x_log10() + 
  scale_y_log10(labels = scales::comma_format()) + 
  labs(title = "Using a 'new' lexicon gives a more polarizing distribution \nof peaceful and confilct terms",
       subtitle = "Top 100 words in each Society-Lexicon group.",
       x = "LOG Rank",
       y = "LOG Frequency")
  
lexicon %>%
  full_join(lexicon.new, by="term", suffix=c(".old", ".new")) %>%
  mutate(lexicon.old = ifelse(is.na(lexicon.old), FALSE, TRUE),
         lexicon.new = ifelse(is.na(lexicon.new), FALSE, TRUE)) %>%
  count(lexicon.old, lexicon.new) %>%
  knitr::kable()
```

```{r}
library(wordcloud)

words <- data %>%
  rename(term = word) %>%
  left_join(lexicon.new, by = "term") %>%
  filter(!is.na(lexicon)) %>%
  group_by(lexicon, term) %>%
  summarise(freq = sum(freq))
  
par(mfrow=c(1, 2))
          
words %>%
  filter(lexicon == "peace") %>%
  with(wordcloud(term, 
                 freq, 
                 min.freq = 1,
                 max.words = 100, 
                 random.order = FALSE, 
                 rot.per = 0, 
                 scale = c(3.2,.5),
                 colors = brewer.pal(8, "Dark2")))

words %>%
  filter(lexicon == "conflict") %>%
  with(wordcloud(term, 
                 freq, 
                 min.freq = 1,
                 max.words = 100, 
                 random.order = FALSE, 
                 rot.per = 0, 
                 scale = c(3.4,.8),
                 colors = brewer.pal(8, "Dark2")))
```

